<?php

namespace Houssem\BackBundle\Repository;

/**
 * ContratVoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratVoitureRepository extends \Doctrine\ORM\EntityRepository
{

}
