<?php

namespace Houssem\FrontBundle\Repository;

/**
 * demandeAnnulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeAnnulationRepository extends \Doctrine\ORM\EntityRepository
{
}
